/**
 * Custom FinaticConnect extension.
 * 
 * This file is protected and will not be overwritten during regeneration.
 * Add custom logic to extend or override generated FinaticConnect behavior.
 */

import { FinaticConnect as GeneratedFinaticConnect } from '../generated/FinaticConnect';
import type { FinaticConnectOptions } from '../generated/FinaticConnect';
import type { SdkConfig } from '../generated/config';
import { getLogger, type Logger } from '../generated/utils/logger';
import { CustomSessionWrapper } from './wrappers/session';
import { CustomBrokersWrapper } from './wrappers/brokers';
import { SessionApi } from '../generated/api/session-api';
import { BrokersApi } from '../generated/api/brokers-api';

/**
 * Custom FinaticConnect class that extends the generated class.
 * Use this to add custom initialization logic or override methods.
 */
export class FinaticConnect extends GeneratedFinaticConnect {
  // Marker to verify custom class is being used
  static readonly __CUSTOM_CLASS__ = true;

  /**
   * Override constructor to use custom wrappers with safe logger
   */
  constructor(options: FinaticConnectOptions) {
    super(options);
    
    // Replace wrappers with custom ones that use safe logger
    // This is needed because the generated wrappers use pino directly
    // which fails in browser environments
    const self = this as any;
    const config = self.config;
    const sdkConfig = self.sdkConfig;
    
    // Replace session wrapper
    const sessionApi = new SessionApi(config);
    self.session = new CustomSessionWrapper(sessionApi, config, sdkConfig);
    
    // Replace brokers wrapper with custom one that uses safe logger
    // Session headers are now handled by the generator, but we still need the safe logger
    const brokersApi = new BrokersApi(config);
    self.brokers = new CustomBrokersWrapper(brokersApi, config, sdkConfig);
  }

  // Static init() method is now handled by the generator with enhanced error handling and session validation
  // init() calls _initSession() (private) to get one-time token, then _startSession() (private) to start session
  // Only init() is exposed to users - startSession() is NOT exposed

  // Phase 2C: All convenience methods (getAllAccounts, getAllOrders, getAllPositions, getAllBalances,
  // getOrderFills, getOrderEvents, getOrderGroups, getPositionLots, getPositionLotFills, disconnectCompany)
  // are now generated by the generator with proper typed input objects, enum coercion, and standard response structure.
}

