/**
 * Custom FinaticConnect extension.
 *
 * This file is protected and will not be overwritten during regeneration.
 * Add custom logic to extend or override generated FinaticConnect behavior.
 */

import { FinaticConnect as GeneratedFinaticConnect } from '../generated/FinaticConnect';
import type { FinaticConnectOptions } from '../generated/FinaticConnect';
import type { SdkConfig } from '../generated/config';
import { getLogger, type Logger } from '../generated/utils/logger';
import { CustomSessionWrapper } from './wrappers/session';
import { CustomBrokersWrapper } from './wrappers/brokers';
import { SessionApi } from '../generated/api/session-api';
import { BrokersApi } from '../generated/api/brokers-api';

/**
 * Custom FinaticConnect class that extends the generated class.
 * Use this to add custom initialization logic or override methods.
 *
 * NOTE: Custom wrappers (CustomSessionWrapper, CustomBrokersWrapper) are provided
 * as examples for extending generated wrappers. The generated wrappers are used
 * by default and include browser-safe logging.
 */
export class FinaticConnect extends GeneratedFinaticConnect {
  // Marker to verify custom class is being used
  static readonly __CUSTOM_CLASS__ = true;

  // Custom wrapper examples (commented out - using generated wrappers by default):
  // To use custom wrappers, uncomment and modify the constructor below:
  //
  // constructor(options: FinaticConnectOptions) {
  //   super(options);
  //
  //   const self = this as any;
  //   const config = self.config;
  //   const sdkConfig = self.sdkConfig;
  //
  //   // Replace with custom wrappers if needed
  //   const sessionApi = new SessionApi(config);
  //   self.session = new CustomSessionWrapper(sessionApi, config, sdkConfig);
  //
  //   const brokersApi = new BrokersApi(config);
  //   self.brokers = new CustomBrokersWrapper(brokersApi, config, sdkConfig);
  // }

  // Static init() method is now handled by the generator with enhanced error handling and session validation
  // init() calls _startSession() (private) directly with the provided token (Client SDK doesn't use _initSession)
  // Only init() is exposed to users - startSession() is NOT exposed

  // Phase 2C: All convenience methods (getAllAccounts, getAllOrders, getAllPositions, getAllBalances,
  // getOrderFills, getOrderEvents, getOrderGroups, getPositionLots, getPositionLotFills, disconnectCompany)
  // are now generated by the generator with proper typed input objects, enum coercion, and standard response structure.
}
